# Generated by Django 5.1.6 on 2025-02-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('servico', models.CharField(max_length=255)),
                ('profissional', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('especie', models.CharField(max_length=255)),
                ('raca', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('peso', models.FloatField()),
                ('observacoes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.FloatField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('autenticado', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='petshop',
        ),
    ]
